---
title: "Distribuzione soci WJ"
author: "Paolo Bosetti"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
library(tmap)
library(sf)
```

# Dati

```{r}
province <- read_tsv("province.txt", na=c(""))
province <- province %>% 
  mutate(PROVINCIA = str_to_upper(PROVINCIA) %>% str_replace_all("[\\s]", "-") %>% str_replace("Roma", "RM"))
soci <- read_csv("Soci_240603.csv")
soci %>% setNames(names(soci) %>% str_replace("Residenza\\s","")) -> soci
soci %>%
  mutate(Provincia = 
           str_to_upper(Provincia) %>% 
           str_replace_all("\\s*\\)", "") %>%
           str_replace_all("(\\w)\\s(\\w)", "\\1-\\2") %>%
           str_replace_all("[\\(\\)]", "")) -> soci
```
Sanitize:

```{r}
soci <- soci %>% 
  filter(Nazione == "IT") %>% 
  left_join(province, by = c("Provincia" = "PROVINCIA")) %>% 
  select(Stato, Città, Cap, Provincia, SIGLA) %>% 
  mutate(SIGLA = ifelse(is.na(SIGLA), Provincia, SIGLA) %>% str_replace("Roma", "RM"))
```

```{r}
soci_n <- soci %>% 
  group_by(SIGLA) %>% 
  summarise(n = n()) %>% 
  arrange(desc(n)) %>% 
  left_join(province, by = c("SIGLA" = "SIGLA")) %>% 
  select(-PROVINCIA) %>%
  rename(Provincia = SIGLA, Regione = REGIONE, Numero = n) %>% 
  select(Regione, Provincia, Numero)
soci_n %>% 
  filter(Numero > 0) %>% 
  knitr::kable()
```

# Mappa

```{r}
shapefile <-  "maps/georef-italy-provincia-millesime.shp"
italy <- read_sf(shapefile)
# italy <- rmapshaper::ms_simplify(italy, keep=0.1)
```

```{r}
map <- italy %>% 
  left_join(soci_n, by = c("prov_sigla" = "Provincia")) %>%
  tm_shape(simplify=0.05) + 
  tm_borders() +
  tm_fill(
    col = "Numero", 
    style = "jenks", 
    title = "Numero soci WJ", 
    textNA="Nessuno", 
    legend.format=list(text.separator = "-")
  )
tmap_mode("plot")
map
```


