project:
  type: website
  preview:
    port: 8080
    host: localhost
  resources:
    - "CNAME"
website:
  title: "Informazioni su WJ"
  site-url: "https://soci.witnessjournal.com"
  description: "Dati sull'Associazione WJ"
  navbar:
    left:
      - text: "Territori"
        href: territori.qmd
      - text: "Situazione Soci"
        href: situazione_soci.qmd
      - text: "Storico"
        href: storico.qmd
format:
  html:
    lang: it-IT
    toc: true
    email-obfuscation: "javascript"
    theme: 
      - wj.scss