---
title: "Storico"
format: html
---

```{r setup}
#| include: false
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	fig.width = 6,
  fig.height = 5,
  fig.align = "center",
  out.width = "100%",
  dpi = 300
)
library(tidyverse)
library(stringr)
library(tmap)
library(sf)
library(glue)
library(plotly)
source("wj_utils.R")

```


:::{.callout-warning}
Pagina in costruzione.
:::



```{r}
soci <- wj_data(wj_tokens()) %>% wj_soci()
```


```{r}
storico <- soci %>% 
  arrange(data_iscrizione) %>% 
  mutate(
    week = format(ymd(data_iscrizione), "%Y-%V"),
    .after = 1
  ) %>% 
  group_by(week) %>%
  summarise(
    Data = last(data_iscrizione) %>% ymd(),
    Soci = n(),
    `Soci in regola` = sum(!deve_rinnovare),
    `Soci da rinnovare` = sum(deve_rinnovare),
    Maschi = sum(genere == "M", na.rm = TRUE),
    Femmine = sum(genere == "F", na.rm = TRUE),
    `Soci in Italia` = sum(nazione == "IT", na.rm = TRUE),
    `Soci all'estero` = sum(nazione != "IT", na.rm = TRUE)
  ) %>% 
  mutate(
    across(-c(week, Data), cumsum)
  )
```



```{r}
prov_count <- soci %>% 
  filter(!is.na(provincia)) %>% 
  arrange(data_iscrizione) %>% 
  mutate(
    week = format(ymd(data_iscrizione), "%Y-%V"),
    .after = 1
  ) %>% 
  group_by(week, provincia) %>% 
  select(provincia, week, data_iscrizione) %>% 
  summarise(
    Numero = n()
  ) %>% 
  pivot_wider(
    names_from = provincia, 
    names_prefix = "prov_",
    values_from = Numero
  ) %>% 
  ungroup() %>% 
  mutate(
    across(2:last_col(), ~replace_na(., 0))
  ) %>%
  mutate(across(2:last_col(), cumsum))

storico <- storico %>% 
  left_join(prov_count) %>% 
  select(-week) %>% 
  write_csv("storico.csv", col_names=TRUE, append=FALSE)
```


## Crescita storica dei soci

Questo grafico riporta la crescita storica dei soci afferenti complessivi e afferenti ai gruppi territoriali più numerosi (con più di sei soci). Il grafico **è interattivo**.

```{r}
#| fig.width: 8
#| fig.height: 4
plt <- storico %>% 
  pivot_longer(
    cols = starts_with("prov_"), 
    names_to = "Provincia", 
    values_to = "Soci locali"
  ) %>% 
  filter(`Soci locali` > 6) %>% 
  ggplot(aes(x=Data)) + 
  geom_line(aes(y=`Soci locali`, color=Provincia)) +
  geom_line(aes(y=Soci, color="Soci totali"), size=1) +
  scale_x_date(
    date_labels = "%Y-%m", 
    date_breaks = "3 month", 
    minor_breaks = "1 month")

ggplotly(plt, width=650, height=400)
```

